/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author stavi
 * 
 */

import java.awt.PopupMenu;
import java.awt.event.ActionEvent;
import javax.swing.*;
import midterm.PatientForm;

@SuppressWarnings("ObsoleteAnnotationSupportedSource")
public class Hospital extends javax.swing.JFrame {

    private PopupMenu popupMenu1;
    private JLabel HosptialLabel;
    private JLabel UsernameLabel;
    private JTextField UsernameTextField1;
    private JLabel jLabel2;
    private JPasswordField UsernamePasswordField1;
    private JButton LoginButton1;
    private JCheckBox PatientCheckBox1;
    private JCheckBox DoctorCheckBox1;
    private JCheckBox jCheckBox1;
    private JPopupMenu jPopupMenu1;
    private JPopupMenu jPopupMenu2;
    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        HosptialLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        UsernamePasswordField1 = new javax.swing.JPasswordField();
        LoginButton1 = new javax.swing.JButton();
        PatientCheckBox1 = new javax.swing.JCheckBox();
        DoctorCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HosptialLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        HosptialLabel.setText("NORTH SIDE HOSPITAL");

        UsernameLabel.setText("Username ID");

        UsernameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        UsernamePasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamePasswordField1ActionPerformed(evt);
            }
        });

        LoginButton1.setText("LOGIN");
        LoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton1ActionPerformed(evt);
            }
        });

        PatientCheckBox1.setText("LOGIN AS PATIENT");

        DoctorCheckBox1.setText("LOGIN AS DOCTOR");
        DoctorCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("LOGIN AS ADMIN");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DoctorCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)
                        .addGap(62, 62, 62)
                        .addComponent(PatientCheckBox1)
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HosptialLabel)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addComponent(UsernameLabel)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoginButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UsernamePasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UsernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(HosptialLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientCheckBox1)
                    .addComponent(DoctorCheckBox1)
                    .addComponent(jCheckBox1))
                .addGap(28, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UsernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UsernamePasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UsernameLabel)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)))
                .addGap(55, 55, 55)
                .addComponent(LoginButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextField1ActionPerformed

    private void UsernamePasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamePasswordField1ActionPerformed

    }//GEN-LAST:event_UsernamePasswordField1ActionPerformed

    private void DoctorCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorCheckBox1ActionPerformed

    private void LoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton1ActionPerformed
        // TODO add your handling code here:
    String username = UsernameTextField1.getText();
    String password = new String(UsernamePasswordField1.getPassword());

    if (PatientCheckBox1.isSelected()) {
        // Open Patient Form
        openPatientForm(username, password);
    } else if (DoctorCheckBox1.isSelected()) {
        // Open Doctor Form
        openDoctorForm(username, password);
    } else if (jCheckBox1.isSelected()) {
        // Open Admin Form (replace "AdminForm" with the actual form class)
        openAdminForm(username, password);
    } else {
        // Handle the case when no checkbox is selected
        JOptionPane.showMessageDialog(this, "Please select a login option.");
    }
}

private void openPatientForm(String username, String password) {
    // Assuming PatientForm is a valid class
    PatientForm patientForm = new PatientForm(username, password);
    patientForm.setVisible(true);
    this.dispose(); // Close the current login form if needed
}

private void openDoctorForm(String username, String password) {
    // Assuming DoctorForm is a valid class
    DoctorForm doctorForm = new DoctorForm(username, password);
    doctorForm.setVisible(true);
    this.dispose(); // Close the current login form if needed
}

private void openAdminForm(String username, String password) {
    // Assuming AdminForm is a valid class
    AdminForm adminForm = new AdminForm (username, password);
    adminForm.setVisible(true);
    this.dispose(); // Close the current login form if needed
} 



    }//GEN-LAST:event_LoginButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
{
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DoctorCheckBox1;
    private javax.swing.JLabel HosptialLabel;
    private javax.swing.JButton LoginButton1;
    private javax.swing.JCheckBox PatientCheckBox1;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPasswordField UsernamePasswordField1;
    private javax.swing.JTextField UsernameTextField1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
